### PR TITLE
github actions: Update pylint for Fedora 33

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related stratis-storage/project#263

### CODE REVIEW

**Review by mulkieran — CHANGES_REQUESTED** [review]
One last thing: for CURRENT DEVELOPMENT, psutil should be bumped to 5.7.2, otherwise, this looks good.

**Review by mulkieran — COMMENTED** [review]
Looks good. Can you pull out commit https://github.com/stratis-storage/testing/pull/14/commits/0ddaf8010fa98acaf5052f24d4dadb22566af2f6 and put it in a separate PR for immediate merging?

**Comment by bgurney-rh** [comment]
@mulkieran ok; that commit is now in #15; I force-pushed to remove that commit from this PR.

**Comment by mulkieran** [comment]
Excellent. Moving to pending in April, we can ignore it until then.

**Comment by bgurney-rh** [comment]
Rebased.

**Pull request closed without merging**
