### PR TITLE
stratisd_cert: Add test_pool_start_by_name

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/stratisd#3079
Related https://github.com/stratis-storage/project/issues/538

### CODE REVIEW

**Comment by bgurney-rh** [comment]
This also increases the D-Bus revision to 4.  (Do not merge until stratis-storage/stratisd#3079 is merged.)

**Comment by mulkieran** [comment]
This should be fixed to adapt to the slightly changed D-Bus interface.

**Comment by bgurney-rh** [comment]
Rebased, folding the D-Bus order fix into the stratisd test patch.

Tested on a build of stratis-storage/stratisd#3079 and stratis-storage/stratis-cli#929; the two new tests and one modified test (StratisdCertify.test_pool_start_stopped) all pass.

**Review by mulkieran — APPROVED** [review]
Looks good.

**Pull request merged**
