### PR TITLE
Update tests to match r4 Manager D-Bus interface

### PR DESCRIPTION
**Pull request by mulkieran**
Related https://github.com/stratis-storage/project/issues/275

Do not change existing tests or add new tests, just adapt to the new CreatePool API.

### CODE REVIEW

**Comment by mulkieran** [comment]
@bgurney-rh Please test against PR https://github.com/stratis-storage/stratisd/pull/2421.

**Review by jbaublitz — APPROVED** [review]

**Review by bgurney-rh — APPROVED** [review]
All tests pass, on a blackbox test run using PRs stratisd 2421, and stratis-cli 730.

**Comment by mulkieran** [comment]
Great! Putting this in pending until we make some adjustments to the CLI PR.

**Comment by mulkieran** [comment]
@bgurney-rh Could you test it again against the same PRs? It should continue to pass w/ no further changes.

**Comment by mulkieran** [comment]
rebased.

**Pull request merged**
