### PR TITLE
stratisd_cert: skip tests that require more devices than provided

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: #122

### CODE REVIEW

**Comment by bgurney-rh** [comment]
Tests skipped when only 2 devices are provided: 6 of 56
Tests skipped when only 1 device is provided: 10 of 56
Tests skipped when no devices are provided: 35 of 56

**Comment by bgurney-rh** [comment]
Rebased.

**Comment by bgurney-rh** [comment]
Squashed the stratisd_cert update into a single commit.

**Comment by bgurney-rh** [comment]
For stratis-cli:

Tests skipped when only 2 devices are provided: 4 of 47
Tests skipped when only 1 device is provided: 8 of 47
Tests skipped when no devices are provided: 32 of 47

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
