### PR TITLE
Add test to create filesystem with specified size

### PR DESCRIPTION
**Pull request by bgurney-rh**
Supersedes: #45 
Related: #43

### CODE REVIEW

**Review by mulkieran — CHANGES_REQUESTED** [review]
This looks good! Might as well carry on and add one more test in ```stratisd_cert.py``` and then start on CLI tests.

**Comment by bgurney-rh** [comment]
If I remember correctly, you wanted me to also add a test for a case where the specified size is too small.

**Review by mulkieran — CHANGES_REQUESTED** [review]
This looks good. If you sqash the commits and force push we can go ahead and merge.

**Comment by bgurney-rh** [comment]
OK; force-pushed into 1 commit.

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
