### PR TITLE
Add tests for stratis-dumpmetadata command

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: #165

### CODE REVIEW

**Comment by bgurney-rh** [comment]
This test requires the stratisd-tools package to be installed, but this is a new package.

**Comment by mulkieran** [comment]
@bgurney-rh What condition will cause it to become unblocked? My understanding was that it was testable as soon as we merged the associated stratisd and spec file changes.

**Comment by bgurney-rh** [comment]
The system running the test needs to install the stratisd-tools package.

Perhaps it's not a blocker for merging this, but it's something that would need to be added to whatever runs the tests.  (One of these would be "stratis-blackbox-run.sh" in the "blackbox" subdirectory of the ci repository.)

**Comment by mulkieran** [comment]
> The system running the test needs to install the stratisd-tools package.
> 
> Perhaps it's not a blocker for merging this, but it's something that would need to be added to whatever runs the tests. (One of these would be "stratis-blackbox-run.sh" in the "blackbox" subdirectory of the ci repository.)

Ok! I think you should queue up those changes then. I believe that when Fedora gating tests are run, every package is installed. So we should simulate that with our own testing.

**Comment by mulkieran** [comment]
@bgurney-rh Please rebase this. I don't think it is blocked.

**Comment by bgurney-rh** [comment]
Rebased.

**Review by mulkieran — APPROVED** [review]

**Comment by bgurney-rh** [comment]
I think I will need to add something to `blackbox/stratis-blackbox-run.sh` to ensure it can run these tests.

**Comment by mulkieran** [comment]
This looks good. Awaiting information on whether tests.yaml file needs to be updated.

**Pull request merged**
